---
- name: Logon to CyberArk Web Services (Management API)
  uri:
    url: "{{ cyberark_api_base_url }}/PasswordVault/API/Auth/{{ cyberark_auth_type }}/Logon"
    method: POST
    status_code: 200
    validate_certs: "{{ cyberark_validate_certs }}"
    headers:
      Content-Type: application/json
    body:
      username: "{{ cyberark_username }}"
      password: "{{ cyberark_password }}"
    body_format: json
  register: cyberark_auth_token
