---
- name: Add Account to CyberArk Core Privileged Access Security (PAS)
  uri:
    url: "{{ cyberark_api_base_url }}/PasswordVault/API/Accounts"
    method: POST
    status_code: 201
    validate_certs: "{{ cyberark_validate_certs }}"
    headers:
      Authorization: "{{ cyberark_auth_token }}"
      Content-Type: application/json
    body:
      name: "{{ cyberark_acct_name }}"
      address: "{{ cyberark_acct_address }}"
      userName: "{{ cyberark_acct_username }}"
      platformId: "{{ cyberark_acct_platformId }}"
      safeName: "{{ cyberark_acct_safeName }}"
      secretType: "{{ cyberark_acct_secretType }}"
      secret: "{{ cyberark_acct_password }}"
      secretManagement:
        automaticManagementEnabled: "{{ cyberark_acct_autoManagement }}"
        manualManagementReason: "{{ cyberark_acct_manualReason }}"
      platformAccountProperties:
        LogonDomain: "{{ cyberark_acct_logonDomain }}"
        Port: "{{ cyberark_acct_port }}"
      remoteMachinesAccess:
        remoteMachines: "{{ cyberark_acct_remoteMachines }}"
        accessRestrictedToRemoteMachines: "{{ cyberark_acct_accessRestricted }}"
    body_format: json